"""add users table and user_id to prospects and products

Revision ID: 0ef171628c44
Revises: f6ae0d261480
Create Date: 2026-03-01 15:08:27.411852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0ef171628c44'
down_revision: Union[str, Sequence[str], None] = 'f6ae0d261480'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.add_column('products', sa.Column('user_id', sa.Integer(), nullable=False))
    op.alter_column('products', 'item_number',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Product SKU item code',
               existing_nullable=False)
    op.alter_column('products', 'name',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Product name',
               existing_nullable=False)
    op.alter_column('products', 'short_description',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Brief product description',
               existing_nullable=True)
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.drop_index(op.f('ix_products_item_number'), table_name='products')
    op.create_index(op.f('ix_products_user_id'), 'products', ['user_id'], unique=False)
    op.create_foreign_key(None, 'products', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('prospects', sa.Column('user_id', sa.Integer(), nullable=True))
    op.alter_column('prospects', 'first_name',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='First name',
               existing_nullable=False)
    op.alter_column('prospects', 'last_name',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Last name',
               existing_nullable=False)
    op.alter_column('prospects', 'email',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Email address (unique identifier)',
               existing_nullable=False)
    op.alter_column('prospects', 'phone_number',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='Phone number',
               existing_nullable=True)
    op.alter_column('prospects', 'position',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Job title',
               existing_nullable=True)
    op.alter_column('prospects', 'company_name',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Company name',
               existing_nullable=True)
    op.alter_column('prospects', 'company_size',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Company size (e.g., 1-10, 11-50, 51-200, etc.)',
               existing_nullable=True)
    op.alter_column('prospects', 'source',
               existing_type=postgresql.ENUM('TRADE_SHOW', 'RIDE_ALONG', 'PROSPECTION', 'RECOMMENDATION', 'OTHER', name='prospectsource'),
               comment=None,
               existing_comment='Origin of the prospect',
               existing_nullable=False)
    op.alter_column('prospects', 'source_notes',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Additional context from source',
               existing_nullable=True)
    op.alter_column('prospects', 'status',
               existing_type=postgresql.ENUM('NEW', 'CONTACTED', 'RESPONDED', 'ARCHIVED', name='prospectstatus'),
               comment=None,
               existing_comment='Current workflow status',
               existing_nullable=False)
    op.drop_index(op.f('ix_prospects_email'), table_name='prospects')
    op.drop_index(op.f('ix_prospects_id'), table_name='prospects')
    op.drop_index(op.f('ix_prospects_source'), table_name='prospects')
    op.drop_index(op.f('ix_prospects_status'), table_name='prospects')
    op.create_index(op.f('ix_prospects_user_id'), 'prospects', ['user_id'], unique=False)
    op.create_index('ix_prospects_user_source', 'prospects', ['user_id', 'source'], unique=False)
    op.create_index('ix_prospects_user_status', 'prospects', ['user_id', 'status'], unique=False)
    op.create_unique_constraint(None, 'prospects', ['email'])
    op.create_foreign_key(None, 'prospects', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'prospects', type_='foreignkey')
    op.drop_constraint(None, 'prospects', type_='unique')
    op.drop_index('ix_prospects_user_status', table_name='prospects')
    op.drop_index('ix_prospects_user_source', table_name='prospects')
    op.drop_index(op.f('ix_prospects_user_id'), table_name='prospects')
    op.create_index(op.f('ix_prospects_status'), 'prospects', ['status'], unique=False)
    op.create_index(op.f('ix_prospects_source'), 'prospects', ['source'], unique=False)
    op.create_index(op.f('ix_prospects_id'), 'prospects', ['id'], unique=False)
    op.create_index(op.f('ix_prospects_email'), 'prospects', ['email'], unique=True)
    op.alter_column('prospects', 'status',
               existing_type=postgresql.ENUM('NEW', 'CONTACTED', 'RESPONDED', 'ARCHIVED', name='prospectstatus'),
               comment='Current workflow status',
               existing_nullable=False)
    op.alter_column('prospects', 'source_notes',
               existing_type=sa.TEXT(),
               comment='Additional context from source',
               existing_nullable=True)
    op.alter_column('prospects', 'source',
               existing_type=postgresql.ENUM('TRADE_SHOW', 'RIDE_ALONG', 'PROSPECTION', 'RECOMMENDATION', 'OTHER', name='prospectsource'),
               comment='Origin of the prospect',
               existing_nullable=False)
    op.alter_column('prospects', 'company_size',
               existing_type=sa.VARCHAR(length=50),
               comment='Company size (e.g., 1-10, 11-50, 51-200, etc.)',
               existing_nullable=True)
    op.alter_column('prospects', 'company_name',
               existing_type=sa.VARCHAR(length=255),
               comment='Company name',
               existing_nullable=True)
    op.alter_column('prospects', 'position',
               existing_type=sa.VARCHAR(length=100),
               comment='Job title',
               existing_nullable=True)
    op.alter_column('prospects', 'phone_number',
               existing_type=sa.VARCHAR(length=20),
               comment='Phone number',
               existing_nullable=True)
    op.alter_column('prospects', 'email',
               existing_type=sa.VARCHAR(length=255),
               comment='Email address (unique identifier)',
               existing_nullable=False)
    op.alter_column('prospects', 'last_name',
               existing_type=sa.VARCHAR(length=100),
               comment='Last name',
               existing_nullable=False)
    op.alter_column('prospects', 'first_name',
               existing_type=sa.VARCHAR(length=100),
               comment='First name',
               existing_nullable=False)
    op.drop_column('prospects', 'user_id')
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_index(op.f('ix_products_user_id'), table_name='products')
    op.create_index(op.f('ix_products_item_number'), 'products', ['item_number'], unique=True)
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    op.alter_column('products', 'short_description',
               existing_type=sa.TEXT(),
               comment='Brief product description',
               existing_nullable=True)
    op.alter_column('products', 'name',
               existing_type=sa.VARCHAR(length=255),
               comment='Product name',
               existing_nullable=False)
    op.alter_column('products', 'item_number',
               existing_type=sa.VARCHAR(length=100),
               comment='Product SKU item code',
               existing_nullable=False)
    op.drop_column('products', 'user_id')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
