"""Add user authentication and update prospect relationships

Revision ID: 1b458353c119
Revises: 8f0d352ea6cd
Create Date: 2026-03-05 17:37:56.393248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1b458353c119'
down_revision: Union[str, Sequence[str], None] = '8f0d352ea6cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_products_user_item', 'products', ['user_id', 'item_number'], unique=True)
    op.add_column('prospect_products', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('prospect_products', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.drop_index(op.f('ix_prospect_products_id'), table_name='prospect_products')
    op.drop_index(op.f('ix_prospect_products_product_id'), table_name='prospect_products')
    op.drop_index(op.f('ix_prospect_products_prospect_id'), table_name='prospect_products')
    op.drop_constraint(op.f('uix_prospect_product'), 'prospect_products', type_='unique')
    op.drop_column('prospect_products', 'added_at')
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.add_column('prospect_products', sa.Column('added_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('uix_prospect_product'), 'prospect_products', ['prospect_id', 'product_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_prospect_products_prospect_id'), 'prospect_products', ['prospect_id'], unique=False)
    op.create_index(op.f('ix_prospect_products_product_id'), 'prospect_products', ['product_id'], unique=False)
    op.create_index(op.f('ix_prospect_products_id'), 'prospect_products', ['id'], unique=False)
    op.drop_column('prospect_products', 'updated_at')
    op.drop_column('prospect_products', 'created_at')
    op.drop_index('ix_products_user_item', table_name='products')
    # ### end Alembic commands ###
