"""add_template_ids_to_campaign

Revision ID: 5f9e9b3cf87d
Revises: a1b2c3d4e5f6
Create Date: 2026-05-08 12:06:30.111883

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f9e9b3cf87d'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaigns', sa.Column('template_initial_id', sa.Integer(), nullable=True))
    op.add_column('campaigns', sa.Column('template_followup_1_id', sa.Integer(), nullable=True))
    op.add_column('campaigns', sa.Column('template_followup_2_id', sa.Integer(), nullable=True))
    op.add_column('campaigns', sa.Column('template_followup_3_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'campaigns', 'email_templates', ['template_initial_id'], ['id'])
    op.create_foreign_key(None, 'campaigns', 'email_templates', ['template_followup_2_id'], ['id'])
    op.create_foreign_key(None, 'campaigns', 'email_templates', ['template_followup_3_id'], ['id'])
    op.create_foreign_key(None, 'campaigns', 'email_templates', ['template_followup_1_id'], ['id'])
    op.drop_index(op.f('ix_email_templates_user_name_unique'), table_name='email_templates')
    op.create_index('ix_email_templates_user_id_name', 'email_templates', ['user_id', 'name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_email_templates_user_id_name', table_name='email_templates')
    op.create_index(op.f('ix_email_templates_user_name_unique'), 'email_templates', ['user_id', 'name'], unique=True)
    op.drop_constraint(None, 'campaigns', type_='foreignkey')
    op.drop_constraint(None, 'campaigns', type_='foreignkey')
    op.drop_constraint(None, 'campaigns', type_='foreignkey')
    op.drop_constraint(None, 'campaigns', type_='foreignkey')
    op.drop_column('campaigns', 'template_followup_3_id')
    op.drop_column('campaigns', 'template_followup_2_id')
    op.drop_column('campaigns', 'template_followup_1_id')
    op.drop_column('campaigns', 'template_initial_id')
    # ### end Alembic commands ###
