"""add_product_food_distribution_fields

Revision ID: 75866cd37a31
Revises: 178352eee4fc
Create Date: 2026-05-29 14:47:20.397269

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75866cd37a31'
down_revision: Union[str, Sequence[str], None] = '178352eee4fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('brand', sa.String(length=255), nullable=True))
    op.add_column('products', sa.Column('category', sa.String(length=100), nullable=True))
    op.add_column('products', sa.Column('formats', sa.String(length=500), nullable=True))
    op.add_column('products', sa.Column('price_range', sa.String(length=100), nullable=True))
    op.add_column('products', sa.Column('certifications', sa.String(length=500), nullable=True))
    op.add_column('products', sa.Column('segments', sa.String(length=255), nullable=True))
    op.add_column('products', sa.Column('is_active', sa.Boolean(), nullable=False, server_default='true'))
    op.create_unique_constraint('uq_prospects_email_user', 'prospects', ['email', 'user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_prospects_email_user', 'prospects', type_='unique')
    op.drop_column('products', 'is_active')
    op.drop_column('products', 'segments')
    op.drop_column('products', 'certifications')
    op.drop_column('products', 'price_range')
    op.drop_column('products', 'formats')
    op.drop_column('products', 'category')
    op.drop_column('products', 'brand')
    # ### end Alembic commands ###
