"""add_company_model

Revision ID: 90849d859011
Revises: 5f9e9b3cf87d
Create Date: 2026-05-14 10:03:19.707671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90849d859011'
down_revision: Union[str, Sequence[str], None] = '5f9e9b3cf87d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('market', sa.String(length=100), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('type_structure', sa.Enum('retail', 'foodservice', 'industry', 'other', name='structuretype'), nullable=True),
    sa.Column('type_contact', sa.Enum('distributor', 'restaurant', 'factory', 'consultant', 'retailer', 'other', name='contacttype'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_user_id'), 'companies', ['user_id'], unique=False)
    op.create_index('ix_companies_user_id_name', 'companies', ['user_id', 'name'], unique=False)
    op.add_column('prospects', sa.Column('company_id', sa.Integer(), nullable=True))
    op.add_column('prospects', sa.Column('source_detail', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_prospects_company_id'), 'prospects', ['company_id'], unique=False)
    op.create_foreign_key(None, 'prospects', 'companies', ['company_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'prospects', type_='foreignkey')
    op.drop_index(op.f('ix_prospects_company_id'), table_name='prospects')
    op.drop_column('prospects', 'source_detail')
    op.drop_column('prospects', 'company_id')
    op.drop_index('ix_companies_user_id_name', table_name='companies')
    op.drop_index(op.f('ix_companies_user_id'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
