"""add_distributor_catalogs

Revision ID: ad3f609ffbd9
Revises: 75866cd37a31
Create Date: 2026-06-02 16:36:11.601421

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad3f609ffbd9'
down_revision: Union[str, Sequence[str], None] = '75866cd37a31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('distributor_catalogs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'company_id', name='uq_catalog_user_company')
    )
    op.create_index(op.f('ix_distributor_catalogs_company_id'), 'distributor_catalogs', ['company_id'], unique=False)
    op.create_index(op.f('ix_distributor_catalogs_user_id'), 'distributor_catalogs', ['user_id'], unique=False)
    op.create_table('distributor_catalog_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('catalog_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['catalog_id'], ['distributor_catalogs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('catalog_id', 'product_id', name='uq_catalog_item_product')
    )
    op.create_index(op.f('ix_distributor_catalog_items_catalog_id'), 'distributor_catalog_items', ['catalog_id'], unique=False)
    op.create_index(op.f('ix_distributor_catalog_items_product_id'), 'distributor_catalog_items', ['product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_distributor_catalog_items_product_id'), table_name='distributor_catalog_items')
    op.drop_index(op.f('ix_distributor_catalog_items_catalog_id'), table_name='distributor_catalog_items')
    op.drop_table('distributor_catalog_items')
    op.drop_index(op.f('ix_distributor_catalogs_user_id'), table_name='distributor_catalogs')
    op.drop_index(op.f('ix_distributor_catalogs_company_id'), table_name='distributor_catalogs')
    op.drop_table('distributor_catalogs')
    # ### end Alembic commands ###
