"""fix_email_templates_index

Revision ID: cee597a7e7c1
Revises: cf7fb0f19371
Create Date: 2026-05-26 19:59:18.307275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cee597a7e7c1'
down_revision: Union[str, Sequence[str], None] = 'cf7fb0f19371'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_email_templates_user_id_name_category'), table_name='email_templates')
    op.create_index('ix_email_templates_user_id_name_category', 'email_templates', ['user_id', 'name', 'category'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_email_templates_user_id_name_category', table_name='email_templates')
    op.create_index(op.f('ix_email_templates_user_id_name_category'), 'email_templates', ['user_id', 'name', 'category'], unique=True)
    # ### end Alembic commands ###
