"""create initial tables

Revision ID: f6ae0d261480
Revises: 
Create Date: 2026-02-28 15:06:42.146964

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6ae0d261480'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_number', sa.String(length=100), nullable=False, comment='Product SKU item code'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Product name'),
    sa.Column('short_description', sa.Text(), nullable=True, comment='Brief product description'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    op.create_index(op.f('ix_products_item_number'), 'products', ['item_number'], unique=True)
    op.create_table('prospects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False, comment='First name'),
    sa.Column('last_name', sa.String(length=100), nullable=False, comment='Last name'),
    sa.Column('email', sa.String(length=255), nullable=False, comment='Email address (unique identifier)'),
    sa.Column('phone_number', sa.String(length=20), nullable=True, comment='Phone number'),
    sa.Column('position', sa.String(length=100), nullable=True, comment='Job title'),
    sa.Column('company_name', sa.String(length=255), nullable=True, comment='Company name'),
    sa.Column('company_size', sa.String(length=50), nullable=True, comment='Company size (e.g., 1-10, 11-50, 51-200, etc.)'),
    sa.Column('market', sa.String(length=100), nullable=True),
    sa.Column('source', sa.Enum('TRADE_SHOW', 'RIDE_ALONG', 'PROSPECTION', 'RECOMMENDATION', 'OTHER', name='prospectsource'), nullable=False, comment='Origin of the prospect'),
    sa.Column('source_notes', sa.Text(), nullable=True, comment='Additional context from source'),
    sa.Column('status', sa.Enum('NEW', 'CONTACTED', 'RESPONDED', 'ARCHIVED', name='prospectstatus'), nullable=False, comment='Current workflow status'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prospects_email'), 'prospects', ['email'], unique=True)
    op.create_index(op.f('ix_prospects_id'), 'prospects', ['id'], unique=False)
    op.create_index(op.f('ix_prospects_source'), 'prospects', ['source'], unique=False)
    op.create_index(op.f('ix_prospects_status'), 'prospects', ['status'], unique=False)
    op.create_table('prospect_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prospect_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['prospect_id'], ['prospects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('prospect_id', 'product_id', name='uix_prospect_product')
    )
    op.create_index(op.f('ix_prospect_products_id'), 'prospect_products', ['id'], unique=False)
    op.create_index(op.f('ix_prospect_products_product_id'), 'prospect_products', ['product_id'], unique=False)
    op.create_index(op.f('ix_prospect_products_prospect_id'), 'prospect_products', ['prospect_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prospect_products_prospect_id'), table_name='prospect_products')
    op.drop_index(op.f('ix_prospect_products_product_id'), table_name='prospect_products')
    op.drop_index(op.f('ix_prospect_products_id'), table_name='prospect_products')
    op.drop_table('prospect_products')
    op.drop_index(op.f('ix_prospects_status'), table_name='prospects')
    op.drop_index(op.f('ix_prospects_source'), table_name='prospects')
    op.drop_index(op.f('ix_prospects_id'), table_name='prospects')
    op.drop_index(op.f('ix_prospects_email'), table_name='prospects')
    op.drop_table('prospects')
    op.drop_index(op.f('ix_products_item_number'), table_name='products')
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.drop_table('products')
    # ### end Alembic commands ###
